### ISSUE TITLE
Skill: (1) Add search to your index action in Rails

### ISSUE THREAD

**Issue by PStanos** [PStanos/tc359_rails_final#6]
Searching on cat name (partial non-case sensitive matching). Sanitizes input to prevent SQL injection, since I am using explicit string query.

**Comment by PStanos** [comment]
@chrisvfritz

**Comment by chrisvfritz** [comment]
Looks good. I like that you made sure to protect yourself from [SQL injection](https://xkcd.com/327/)! To help you be lazy in the future, there's one refactor I'd like you to do. 

Rails' ActiveRecord layer can actually do that sanitation for you if you pass `params[:name]` as a separate parameter to be injected by into your custom SQL. Below is a little one-liner we could put in the `index` action to replace your `search` action:

``` ruby
def index
  @cats = params[:name] ? Cat.where('name LIKE ?', "%#{params[:name]}%") : Cat.all
end
```

As a little bonus, we can even make this case insensitive with:

``` ruby
Cat.where('LOWER(name) LIKE LOWER(?)', "%#{params[:name]}%")
```

Or, if you're using a database like PostgreSQL that supports `ILIKE` (which is a case-insensitive version of `LIKE`):

``` ruby
Cat.where('name ILIKE ?', "%#{params[:name]}%")
```

Let me know when you've refactored this and I'll take another look. :smiley:

**Comment by PStanos** [comment]
Thanks for the advice! The search code is much simpler now. @chrisvfritz

**Comment by chrisvfritz** [comment]
:+1: Righteous!
